# Generated by Django 4.2.6 on 2023-10-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('meat', models.BooleanField(verbose_name='Говядина')),
                ('chicken', models.BooleanField(verbose_name='Курица')),
                ('cheese', models.BooleanField(verbose_name='Сыр')),
                ('tomato', models.BooleanField(verbose_name='Помидоры')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
